import type { SqliteCodexSessionRegistry } from "./codex-session-registry.js";

export type ManagedAgentsStore = Pick<SqliteCodexSessionRegistry,
  | "deleteAgentSpawnSuggestionState"
  | "getActiveAuthAccount"
  | "getAgentRuntimeProfile"
  | "getAgentRuntimeProfileByOwnerAgent"
  | "getAgentSpawnPolicy"
  | "getAgentSpawnSuggestionState"
  | "getAgentWorkItem"
  | "getAgentWorkspacePolicy"
  | "getAgentWorkspacePolicyByOwnerAgent"
  | "getAuthAccount"
  | "getManagedAgent"
  | "getOrganization"
  | "getPrincipal"
  | "listAgentAuditLogsByOrganization"
  | "listAuthAccounts"
  | "listAgentHandoffsByAgent"
  | "listAgentMailboxEntriesByAgent"
  | "listAgentMessagesByAgent"
  | "listAgentSpawnSuggestionStatesByOrganization"
  | "listAgentWorkItemsByOwnerPrincipal"
  | "listAgentWorkItemsByParentWorkItem"
  | "listAgentWorkItemsByTargetAgent"
  | "listManagedAgentsByOrganization"
  | "listManagedAgentsByOwnerPrincipal"
  | "listOrganizationsByOwnerPrincipal"
  | "listThirdPartyProviderModels"
  | "listThirdPartyProviders"
  | "saveAgentAuditLog"
  | "saveAgentRuntimeProfile"
  | "saveAgentSpawnPolicy"
  | "saveAgentSpawnSuggestionState"
  | "saveAgentWorkItem"
  | "saveAgentWorkspacePolicy"
  | "saveManagedAgent"
  | "saveOrganization"
  | "savePrincipal"
  | "saveThirdPartyProvider"
  | "saveThirdPartyProviderModel"
>;

export type ManagedAgentCoordinationStore = Pick<SqliteCodexSessionRegistry,
  | "claimNextAgentMailboxEntry"
  | "getActiveAgentExecutionLeaseByRun"
  | "getAgentHandoff"
  | "getAgentMailboxEntry"
  | "getAgentMessage"
  | "getAgentRun"
  | "getAgentRuntimeProfile"
  | "getAgentRuntimeProfileByOwnerAgent"
  | "getAgentWorkItem"
  | "getAgentWorkspacePolicy"
  | "getAgentWorkspacePolicyByOwnerAgent"
  | "getManagedAgent"
  | "getManagedAgentNode"
  | "getOrganization"
  | "getPrincipal"
  | "listAgentHandoffsByAgent"
  | "listAgentHandoffsByWorkItem"
  | "listAgentMailboxEntriesByAgent"
  | "listAgentMessagesByAgent"
  | "listAgentMessagesByWorkItem"
  | "listAgentRunsByWorkItem"
  | "listAgentWorkItemsByOwnerPrincipal"
  | "listAgentWorkItemsByParentWorkItem"
  | "listAgentWorkItemsByTargetAgent"
  | "listManagedAgentsByOrganization"
  | "saveAgentHandoff"
  | "saveAgentExecutionLease"
  | "saveAgentMailboxEntry"
  | "saveAgentMessage"
  | "saveManagedAgentNode"
  | "saveAgentRun"
  | "saveAgentWorkItem"
>;

export type ManagedAgentSchedulerStore = Pick<SqliteCodexSessionRegistry,
  | "claimNextRunnableAgentWorkItem"
  | "getActiveAgentExecutionLeaseByRun"
  | "getManagedAgentNode"
  | "getAgentRun"
  | "getAgentWorkItem"
  | "getManagedAgent"
  | "getOrganization"
  | "getPrincipal"
  | "listAgentExecutionLeasesByRun"
  | "listAgentRunsByWorkItem"
  | "listManagedAgentNodesByOrganization"
  | "listAgentRunsByOwnerPrincipal"
  | "listStaleActiveAgentRuns"
  | "saveAgentExecutionLease"
  | "saveManagedAgentNode"
  | "saveAgentRun"
  | "saveAgentWorkItem"
>;

export type ManagedAgentNodeStore = Pick<SqliteCodexSessionRegistry,
  | "saveAgentExecutionLease"
  | "saveAgentRun"
  | "saveAgentWorkItem"
  | "getAgentRun"
  | "getAgentWorkItem"
  | "getManagedAgent"
  | "getManagedAgentNode"
  | "getOrganization"
  | "getPrincipal"
  | "listAgentExecutionLeasesByNode"
  | "listManagedAgentNodesByOrganization"
  | "listOrganizationsByOwnerPrincipal"
  | "saveManagedAgentNode"
>;

export type ManagedAgentExecutionLeaseStore = Pick<SqliteCodexSessionRegistry,
  | "getAgentExecutionLease"
  | "getActiveAgentExecutionLeaseByRun"
  | "listAgentExecutionLeasesByNode"
  | "listAgentExecutionLeasesByRun"
  | "saveAgentExecutionLease"
>;

export type ManagedAgentExecutionStateStore = Pick<SqliteCodexSessionRegistry,
  | "getAgentWorkItem"
  | "getManagedAgent"
  | "getPrincipal"
  | "getSessionTaskSettings"
  | "listAgentMessagesByWorkItem"
  | "saveAgentWorkItem"
  | "saveManagedAgent"
  | "saveSessionTaskSettings"
>;

export type ManagedAgentWorkerStore = Pick<SqliteCodexSessionRegistry,
  | "getActiveAgentExecutionLeaseByRun"
  | "getAgentRun"
  | "getAgentWorkItem"
  | "getManagedAgent"
  | "getManagedAgentNode"
  | "getOrganization"
  | "getPrincipal"
  | "listAgentMessagesByWorkItem"
  | "listAgentExecutionLeasesByNode"
  | "listAgentExecutionLeasesByRun"
  | "listManagedAgentNodesByOrganization"
  | "listOrganizationsByOwnerPrincipal"
  | "saveManagedAgentNode"
  | "saveAgentExecutionLease"
  | "saveAgentRun"
  | "saveAgentWorkItem"
  | "saveManagedAgent"
>;
