export function createDom() {
  const conversation = document.getElementById("conversation");

  return {
    appShell: document.getElementById("app-shell"),
    sidebar: document.getElementById("sidebar"),
    sidebarBackdrop: document.getElementById("sidebar-backdrop"),
    sidebarCollapseButton: document.getElementById("sidebar-collapse-button"),
    sidebarResizeHandle: document.getElementById("sidebar-resize-handle"),
    workspaceSidebarToggle: document.getElementById("workspace-sidebar-toggle"),
    form: document.getElementById("task-form"),
    goalInput: document.getElementById("goal-input"),
    submitButton: document.getElementById("submit-button"),
    cancelButton: document.getElementById("cancel-button"),
    forkThreadButton: document.getElementById("fork-thread-button"),
    newThreadButton: document.getElementById("new-thread-button"),
    threadSearchInput: document.getElementById("thread-search-input"),
    threadList: document.getElementById("thread-list"),
    threadEmpty: document.getElementById("thread-empty"),
    workspaceToolsToggle: document.getElementById("workspace-tools-toggle"),
    workspaceToolsBackdrop: document.getElementById("workspace-tools-backdrop"),
    workspaceToolsClose: document.getElementById("workspace-tools-close"),
    workspaceToolsPanel: document.getElementById("workspace-tools-panel"),
    conversation,
    workspaceTitle: document.getElementById("workspace-title"),
    workspaceCopy: document.getElementById("workspace-copy"),
    activeThreadLabel: document.getElementById("active-thread-label"),
    modelSelect: document.getElementById("model-select"),
    reasoningSelect: document.getElementById("reasoning-select"),
    approvalSelect: document.getElementById("approval-select"),
    settingsNote: document.getElementById("settings-note"),
    runtimeConfigNote: document.getElementById("runtime-config-note"),
    emptyThreadMarkup: conversation.innerHTML,
  };
}
