export function createDom() {
  const conversation = document.getElementById("conversation");

  return {
    appShell: document.getElementById("app-shell"),
    sidebar: document.getElementById("sidebar"),
    sidebarBackdrop: document.getElementById("sidebar-backdrop"),
    sidebarCollapseButton: document.getElementById("sidebar-collapse-button"),
    sidebarResizeHandle: document.getElementById("sidebar-resize-handle"),
    workspaceSidebarToggle: document.getElementById("workspace-sidebar-toggle"),
    form: document.getElementById("task-form"),
    goalInput: document.getElementById("goal-input"),
    submitButton: document.getElementById("submit-button"),
    cancelButton: document.getElementById("cancel-button"),
    newThreadButton: document.getElementById("new-thread-button"),
    threadSearchInput: document.getElementById("thread-search-input"),
    historyRefreshButton: document.getElementById("history-refresh-button"),
    historySyncCopy: document.getElementById("history-sync-copy"),
    threadList: document.getElementById("thread-list"),
    threadEmpty: document.getElementById("thread-empty"),
    workspaceToolsToggle: document.getElementById("workspace-tools-toggle"),
    workspaceToolsBackdrop: document.getElementById("workspace-tools-backdrop"),
    workspaceToolsClose: document.getElementById("workspace-tools-close"),
    workspaceToolsPanel: document.getElementById("workspace-tools-panel"),
    resetSessionButton: document.getElementById("reset-session-button"),
    forkSessionButton: document.getElementById("fork-session-button"),
    requestMeta: document.getElementById("request-meta"),
    conversation,
    workspaceTitle: document.getElementById("workspace-title"),
    workspaceCopy: document.getElementById("workspace-copy"),
    activeWorkflowLabel: document.getElementById("active-workflow-label"),
    activeRoleLabel: document.getElementById("active-role-label"),
    activeThreadLabel: document.getElementById("active-thread-label"),
    modelInput: document.getElementById("model-input"),
    reasoningSelect: document.getElementById("reasoning-select"),
    approvalSelect: document.getElementById("approval-select"),
    settingsNote: document.getElementById("settings-note"),
    settingsSectionButtons: [...document.querySelectorAll("[data-settings-section]")],
    settingsPanels: [...document.querySelectorAll("[data-settings-panel]")],
    workflowInputs: [...document.querySelectorAll('input[name="workflow"]')],
    roleInputs: [...document.querySelectorAll('input[name="role"]')],
    emptyThreadMarkup: conversation.innerHTML,
  };
}
